"""
Interactive personalisation — tells the scraper what roles and countries YOU want.
    python personalize.py

Either type the roles yourself, or point it at your CV and let the local LLM
(Ollama) suggest roles + priority keywords. Writes user_config.py, which
overrides the defaults in config.py. Re-run any time to change your search.
"""
from __future__ import annotations
import json, re, sys
from pathlib import Path

import requests
import yaml

ROOT = Path(__file__).parent
USER_CONFIG = ROOT / "user_config.py"
RESUME_YAML = ROOT / "Q-Rattor" / "resume_data.yaml"
OLLAMA_URL = "http://localhost:11434/api/chat"
OLLAMA_MODEL = "qwen2.5:7b"

# label -> LinkedIn geoId, Indeed subdomain, Glassdoor code, location-priority terms
REGIONS = {
    "ireland":      dict(li="104738515", indeed="ie", glassdoor="ie", loc=["dublin", "cork", "galway", "limerick", "ireland"]),
    "uk":           dict(li="101165590", indeed="uk", glassdoor="uk", loc=["london", "manchester", "edinburgh", "united kingdom"]),
    "india":        dict(li="102713980", indeed="in", glassdoor="in", loc=["bengaluru", "bangalore", "hyderabad", "chennai", "pune", "india"]),
    "uae":          dict(li="104305776", indeed="ae", glassdoor="ae", loc=["dubai", "abu dhabi", "uae"]),
    "saudi_arabia": dict(li="101004422", indeed="sa", glassdoor=None, loc=["riyadh", "jeddah", "saudi"]),
    "us":           dict(li="103644278", indeed=None, glassdoor="us", loc=["united states"]),
    "europe":       dict(li="91000000",  indeed=None, glassdoor=None, loc=["germany", "netherlands", "france", "europe"]),
}

SENIOR_WORDS = ["senior", "Sr.", "Sr ", "staff", "principal", "lead", "manager",
                "director", "head of", "VP", "vice president"]
BASE_EXCLUDE = ["sales", "marketing", "recruiter", "HR"]


# ── Prompts ───────────────────────────────────────────────────────────────────
def ask(prompt: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    ans = input(f"{prompt}{hint}: ").strip()
    return ans or default

def yes(prompt: str, default: bool = False) -> bool:
    ans = ask(prompt + (" (Y/n)" if default else " (y/N)")).lower()
    return default if not ans else ans.startswith("y")

def split_list(s: str) -> list[str]:
    return [x.strip() for x in re.split(r"[,\n;]", s) if x.strip()]


# ── CV → roles via Ollama ─────────────────────────────────────────────────────
def read_cv(path: Path) -> str:
    if path.suffix.lower() == ".pdf":
        from pypdf import PdfReader
        return "\n".join(page.extract_text() or "" for page in PdfReader(path).pages)
    if path.suffix.lower() in (".yaml", ".yml"):
        return yaml.safe_dump(yaml.safe_load(path.read_text(encoding="utf-8")), sort_keys=False)
    return path.read_text(encoding="utf-8", errors="ignore")

def resume_yaml_is_filled() -> bool:
    if not RESUME_YAML.exists():
        return False
    data = yaml.safe_load(RESUME_YAML.read_text(encoding="utf-8")) or {}
    return data.get("personal", {}).get("name", "Your Name") != "Your Name"

def suggest_from_cv(cv_text: str) -> dict | None:
    prompt = (
        "Here is a candidate's CV:\n\n" + cv_text[:8000] + "\n\n"
        "Suggest what this person should search for on job boards. Return JSON:\n"
        '{"roles": ["6-10 specific, commonly used job titles they are a realistic fit for"],\n'
        ' "priority_keywords": ["8-15 skills/domains from the CV that make a job a strong match"],\n'
        ' "seniority": "entry" | "mid" | "senior"}\n'
        "Roles must be real job-board titles (e.g. 'Data Engineer'), not descriptions. "
        "Base everything strictly on the CV."
    )
    try:
        resp = requests.post(OLLAMA_URL, json={
            "model": OLLAMA_MODEL, "stream": False, "format": "json",
            "options": {"temperature": 0.2},
            "messages": [{"role": "user", "content": prompt}],
        }, timeout=300)
        resp.raise_for_status()
        out = json.loads(resp.json()["message"]["content"])
        if out.get("roles"):
            return out
    except Exception as exc:
        print(f"  Couldn't reach the local LLM ({exc}).")
    return None


# ── Build config values ───────────────────────────────────────────────────────
def build_queries(roles: list[str], internships: bool) -> list[str]:
    # Group roles 4 per query — fewer queries = faster runs, less bot detection
    queries = [" OR ".join(f'"{r}"' for r in roles[i:i + 4]) for i in range(0, len(roles), 4)]
    if internships:
        core = " OR ".join(f'"{r}"' for r in roles[:6])
        queries.append(f'({core}) AND ("intern" OR "internship" OR "graduate")')
    return queries

def write_user_config(values: dict) -> None:
    lines = [
        "# Generated by personalize.py — re-run it to change, or edit by hand.",
        "# Anything set here overrides the same name in config.py.",
        "",
    ]
    for key, val in values.items():
        lines.append(f"{key} = {json.dumps(val, indent=4, ensure_ascii=False)}")
        lines.append("")
    USER_CONFIG.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    print("\n── joobScript: personalise your job search ──\n")

    # 1. Roles — typed, or suggested from the CV
    roles: list[str] = []
    priority: list[str] = []
    seniority = ""
    typed = ask("Roles you want, comma-separated (or press Enter to let AI pick from your CV)")
    if typed:
        roles = split_list(typed)
    else:
        default_cv = str(RESUME_YAML) if resume_yaml_is_filled() else ""
        while not roles:
            cv_path = ask("Path to your CV (.pdf, .txt, .md or resume_data.yaml)", default_cv).strip('"\'')
            if not cv_path or not Path(cv_path).expanduser().exists():
                print("  File not found — try again (you can drag the file into this window).")
                continue
            print("  Reading your CV and asking the local LLM for roles (can take a minute)...")
            suggestion = suggest_from_cv(read_cv(Path(cv_path).expanduser()))
            if not suggestion:
                roles = split_list(ask("Type your roles instead, comma-separated"))
                break
            print("\n  Suggested roles:    " + ", ".join(suggestion["roles"]))
            print("  Priority keywords:  " + ", ".join(suggestion.get("priority_keywords", [])))
            print("  Seniority guess:    " + suggestion.get("seniority", "?") + "\n")
            if yes("Use these?", default=True):
                roles = suggestion["roles"]
                priority = suggestion.get("priority_keywords", [])
                seniority = suggestion.get("seniority", "")
            else:
                roles = split_list(ask("Type the roles you want, comma-separated"))

    # 2. Internships / graduate roles
    internships = yes("Also search internships / graduate roles?", default=False)

    # 3. Countries
    labels = list(REGIONS)
    print("\nWhere do you want to work?")
    for i, label in enumerate(labels, 1):
        print(f"  {i}. {label.upper() if len(label) <= 3 else label.replace('_', ' ').title()}")
    picks = split_list(ask("Pick numbers, comma-separated", "1"))
    chosen = [labels[int(p) - 1] for p in picks if p.isdigit() and 1 <= int(p) <= len(labels)] or ["ireland"]

    # 4. Seniority → what gets filtered out
    levels = {"1": "entry", "2": "mid", "3": "senior"}
    default_level = {v: k for k, v in levels.items()}.get(seniority, "1")
    level = levels.get(ask("\nYour level: 1) entry/graduate  2) mid  3) senior", default_level), "entry")
    exclude = BASE_EXCLUDE + (SENIOR_WORDS if level == "entry" else
                              ["principal", "director", "head of", "VP", "vice president"] if level == "mid" else [])

    # 5. Priority keywords (★ + sorted to the top)
    if not priority:
        priority = split_list(ask("\nKeywords that make a job a top match (skills/domains), comma-separated",
                                  ", ".join(roles[:3])))
    if internships:
        priority += ["intern", "internship", "graduate"]

    values = {
        "SEARCH_QUERIES":      build_queries(roles, internships),
        "LINKEDIN_GEOS":       {c: REGIONS[c]["li"] for c in chosen},
        "INDEED_COUNTRIES":    [REGIONS[c]["indeed"] for c in chosen if REGIONS[c]["indeed"]],
        "GLASSDOOR_COUNTRIES": [REGIONS[c]["glassdoor"] for c in chosen if REGIONS[c]["glassdoor"]],
        "LOCATION_PRIORITY":   [t for c in chosen for t in REGIONS[c]["loc"]],
        "PRIORITY_KEYWORDS":   priority,
        "EXCLUDE_KEYWORDS":    exclude,
    }
    write_user_config(values)

    print(f"\nSaved to {USER_CONFIG.name}:")
    print("  Queries:   " + "\n             ".join(values["SEARCH_QUERIES"]))
    print("  Regions:   " + ", ".join(chosen))
    print("  Excluding: " + ", ".join(exclude))
    if level != "entry":
        print("\n  Note: Q-Rattor/pipeline.py skips resumes for senior/lead roles — remove that check"
              "\n  in main() (search 'Skipping (senior-level)') if you want them.")
    print("\nDone. Run the full pipeline with run_daily.py.\n")


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        sys.exit("\nCancelled — nothing saved.")
